alias ws='cd ~/workspace'
alias ff='find . -iname'
alias gone='git log --oneline'
alias rg='grep -HrnIF --color=always'
alias more='less'
alias fw='cd ~/workspace/smalhotra-linux-devel/TestCenter/framework'
alias tc='cd ~/workspace/smalhotra-linux-devel/TestCenter'
alias pc='p4 changes -s pending -u smalhotra -L'
alias sc='p4 changes -s submitted -u smalhotra -L'
alias scs='p4 changes -s submitted -u smalhotra'
